// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKO6FuNKD94rlMhy0JHvTyustU10r3NO8',
    appId: '1:68569529961:web:8b8761cef64da85505acf8',
    messagingSenderId: '68569529961',
    projectId: 'social-app-e40c0',
    authDomain: 'social-app-e40c0.firebaseapp.com',
    databaseURL: 'https://social-app-e40c0-default-rtdb.firebaseio.com',
    storageBucket: 'social-app-e40c0.appspot.com',
    measurementId: 'G-GP5GT98MLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpY4QgoZKKNn0yvCNij5Vjy6H8XTGggpc',
    appId: '1:68569529961:android:e1caba88b04fa4dd05acf8',
    messagingSenderId: '68569529961',
    projectId: 'social-app-e40c0',
    databaseURL: 'https://social-app-e40c0-default-rtdb.firebaseio.com',
    storageBucket: 'social-app-e40c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5XyQtywlWQCPbjidS57AvgYYIqORcig0',
    appId: '1:68569529961:ios:19987a971bb351f405acf8',
    messagingSenderId: '68569529961',
    projectId: 'social-app-e40c0',
    databaseURL: 'https://social-app-e40c0-default-rtdb.firebaseio.com',
    storageBucket: 'social-app-e40c0.appspot.com',
    androidClientId: '68569529961-rl2u9m2g85j60t4t4n7uh08a3hllic63.apps.googleusercontent.com',
    iosClientId: '68569529961-8bl2kekq4elecj7rb7cnidppov8vhec5.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5XyQtywlWQCPbjidS57AvgYYIqORcig0',
    appId: '1:68569529961:ios:19987a971bb351f405acf8',
    messagingSenderId: '68569529961',
    projectId: 'social-app-e40c0',
    databaseURL: 'https://social-app-e40c0-default-rtdb.firebaseio.com',
    storageBucket: 'social-app-e40c0.appspot.com',
    androidClientId: '68569529961-rl2u9m2g85j60t4t4n7uh08a3hllic63.apps.googleusercontent.com',
    iosClientId: '68569529961-8bl2kekq4elecj7rb7cnidppov8vhec5.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );
}
